$LOCK_CMD = pidof hyprlock || hyprlock --grace 10 # Prevent multiple hyprlock instances
$AFTER_SLEEP_CMD = hyprctl keyword input:numlock_by_default false && hyprctl keyword input:numlock_by_default true && hyprctl dispatch dpms on; sleep 0.3; hyprctl dispatch dpms on

general {
    lock_cmd = $LOCK_CMD
    # before_sleep_cmd = loginctl lock-session   # Lock before suspend (alternative)
    before_sleep_cmd = $LOCK_CMD                # Lock before suspend
    after_sleep_cmd = $AFTER_SLEEP_CMD          # Turn on display after sleep to avoid double key press
}

# listener {
#     timeout = 150                                # 2.5 min
#     on-timeout = brightnessctl -s set 10         # Set monitor backlight to minimum (avoid 0 for OLED)
#     on-resume = brightnessctl -r                 # Restore monitor backlight
# }

## Keyboard backlight control (comment out if not needed)
# listener { 
#     timeout = 150                                          # 2.5 min
#     on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 # Turn off keyboard backlight
#     on-resume = brightnessctl -rd rgb:kbd_backlight        # Restore keyboard backlight
# }

listener {
    timeout = 300                                 # 5 min
    on-timeout = $LOCK_CMD                        # Lock screen after timeout
}

listener {
    timeout = 600                                                     # 10 min
    on-timeout = hyprctl dispatch dpms off                            # Turn off screen after timeout
    on-resume = hyprctl dispatch dpms on && brightnessctl -r          # Turn on screen and restore brightness after activity
}

listener {
    timeout = 1200                                # 20 min
    on-timeout = systemctl suspend                # Suspend PC after timeout
}
