max-gamma = 150

profile {
    time = 7:00
    identity = true
	gamma = 1
}

profile {
    time = 22:00
    temperature = 5800
    gamma = 0.9
}

profile {
	time = 22:30
	temperature = 5200
	gamma = 0.8
}
