#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

# Set nvim as default editor
env = EDITOR,nvim

# NVIDIA REQUIRED ENV VARS FROM WIKI
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Cursor theme
env = XCURSOR_THEME,Win11OS
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# QT apps styling (like dolphin)
env = QT_QPA_PLATFORMTHEME,qt6ct
