################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=HDMI-A-1,1920x1080@180,auto,1
#monitor=HDMI-A-1,disabled
#monitor=HEADLESS-1,1920x1200@60,auto,1
