##############################
### WINDOW- AND LAYERRULES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}

# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

windowrule {
  name = spotify
  match:class = Spotify
  workspace = special:spotify
}

windowrule {
  name = maximized
  match:class = .*
  match:fullscreen = 1
  border_color = rgb(FF0000)
}

windowrule {
  name = opacity
  match:class = .*
  opacity = 0.88 0.78
}


windowrule {
  name = filepicker
  #match:title = ^(Open File|Open|Save|Save As|Export|Import|Choose File|Rename)
  match:class = xdg-desktop-portal-gtk
  float = on
  #center = on
}




layerrule {
  name = rofi
  match:namespace = rofi
  dim_around = on
  animation = popin
}

layerrule {
  name = osd-effects
  match:namespace = swayosd
  
  blur = on
  ignore_alpha = 0
  animation = slidevert
  #order = 50
}

layerrule {
  name = waybar
  match:namespace = waybar
  #dim_around = on
  blur = true
  #xray = 1
  ignore_alpha = 0
}



# Rofi has shadow
#windowrulev2 = shadow, class:^(rofi)$
