$image = {{image}}

$source_color_darkened = rgba({{colors.source_color.default.hex | to_color | lighten: 5.0 | replace: "#", "" }}ff)

################################
# RGBA
################################
<* for name, value in colors *>
${{name}} = rgba({{value.default.hex_stripped}}ff)<* endfor *>



################################
# Saturated, rgba
################################
<* for name, value in colors *>
${{name}}_saturated = rgba({{ value.default.hex | to_color | set_saturation: 100.0 | replace: "#", "" }}ff)<* endfor *>



################################
# Desaturated, rgba
################################
<* for name, value in colors *>
${{name}}_desaturated = rgba({{ value.default.hex | to_color | saturate: -50.0, "hsl" | replace: "#", "" }}ff)<* endfor *>



################################
# RAW RGB (without alpha)
################################
<* for name, value in colors *>
${{name}}_raw = {{value.default.hex_stripped}}<* endfor *>

